// Seed data for MongoDB
// Run this in MongoDB shell or use mongosh to populate initial data

db.users.insertMany([
  {
    name: "Admin User",
    email: "admin@dine-in.com",
    password: "$2a$10$D9Z.TP.B.4KM/0H6Hc1tKe7.Z5q5.q5q5q5q5q5q5q5q5q5q5q5q5q5", // password123
    role: "admin",
    phone: "+1 (555) 000-0001",
        name: "French Onion Soup",
    createdAt: new Date(),
        description: "Classic caramelized onion soup with toasted bread and melted cheese",
        price: 32.00,
        image: "https://via.placeholder.com/300x200?text=French+Onion+Soup",
        stockQuantity: 35,
        thresholdLevel: 5,
        isAvailable: true,
        preparationTime: 10,
        isVegetarian: true,
        isSpicy: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Minestrone Soup",
        category: "appetizers",
        description: "Hearty vegetable and bean soup in tomato broth",
        price: 28.00,
        image: "https://via.placeholder.com/300x200?text=Minestrone+Soup",
        stockQuantity: 30,
        thresholdLevel: 5,
        isAvailable: true,
        preparationTime: 10,
        isVegetarian: true,
        isSpicy: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Chicken Wings",
        category: "appetizers",
        description: "Crispy wings tossed in house hot sauce",
        price: 42.00,
        image: "https://via.placeholder.com/300x200?text=Chicken+Wings",
        stockQuantity: 45,
        thresholdLevel: 8,
        isAvailable: true,
        preparationTime: 12,
        isVegetarian: false,
        isSpicy: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Loaded Nachos",
        category: "appetizers",
        description: "Corn chips with cheese, salsa, and jalapenos",
        price: 45.00,
        image: "https://via.placeholder.com/300x200?text=Loaded+Nachos",
        stockQuantity: 40,
        thresholdLevel: 6,
        isAvailable: true,
        preparationTime: 10,
        isVegetarian: true,
        isSpicy: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Bruschetta",
        category: "appetizers",
        description: "Toasted bread topped with tomato, basil, and olive oil",
        price: 34.00,
        image: "https://via.placeholder.com/300x200?text=Bruschetta",
        stockQuantity: 35,
        thresholdLevel: 5,
        isAvailable: true,
        preparationTime: 8,
        isVegetarian: true,
        isSpicy: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Mozzarella Sticks",
        category: "appetizers",
        description: "Golden fried mozzarella with marinara dip",
        price: 36.00,
        image: "https://via.placeholder.com/300x200?text=Mozzarella+Sticks",
        stockQuantity: 30,
        thresholdLevel: 5,
        isAvailable: true,
        preparationTime: 9,
        isVegetarian: true,
        isSpicy: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Caesar Salad",
        category: "appetizers",
        description: "Fresh romaine lettuce with Caesar dressing and croutons",
        price: 30.00,
        image: "https://via.placeholder.com/300x200?text=Caesar+Salad",
        stockQuantity: 50,
        thresholdLevel: 5,
        isAvailable: true,
        preparationTime: 5,
        isVegetarian: true,
        isSpicy: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Garden Salad",
        category: "appetizers",
        description: "Mixed greens, tomatoes, cucumber, and house vinaigrette",
        price: 26.00,
        image: "https://via.placeholder.com/300x200?text=Garden+Salad",
        stockQuantity: 40,
        thresholdLevel: 5,
        isAvailable: true,
        preparationTime: 5,
        isVegetarian: true,
        isSpicy: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Caprese Salad",
        category: "appetizers",
        description: "Fresh mozzarella, tomatoes, basil, and balsamic glaze",
        price: 38.00,
        image: "https://via.placeholder.com/300x200?text=Caprese+Salad",
        stockQuantity: 30,
        thresholdLevel: 5,
        isAvailable: true,
        preparationTime: 6,
        isVegetarian: true,
        isSpicy: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Slider Trio",
        category: "appetizers",
        description: "Three mini beef sliders with caramelized onions",
        price: 44.00,
        image: "https://via.placeholder.com/300x200?text=Slider+Trio",
        stockQuantity: 28,
        thresholdLevel: 5,
        isAvailable: true,
        preparationTime: 12,
        isVegetarian: false,
        isSpicy: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Stuffed Jalapenos",
        category: "appetizers",
        description: "Jalapenos stuffed with cream cheese and herbs",
        price: 33.00,
        image: "https://via.placeholder.com/300x200?text=Stuffed+Jalapenos",
        stockQuantity: 26,
        thresholdLevel: 5,
        isAvailable: true,
        preparationTime: 10,
        isVegetarian: true,
        isSpicy: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Spring Rolls",
        category: "appetizers",
        description: "Crispy vegetable spring rolls with sweet chili dip",
        price: 29.00,
        image: "https://via.placeholder.com/300x200?text=Spring+Rolls",
        stockQuantity: 36,
        thresholdLevel: 5,
        isAvailable: true,
        preparationTime: 8,
        isVegetarian: true,
        isSpicy: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Ribeye Steak",
        category: "mains",
        description: "Grilled ribeye steak with herb butter",
        price: 145.00,
        image: "https://via.placeholder.com/300x200?text=Ribeye+Steak",
        stockQuantity: 25,
        thresholdLevel: 5,
        isAvailable: true,
        preparationTime: 22,
        isVegetarian: false,
        isSpicy: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Filet Mignon",
        category: "mains",
        description: "Tenderloin steak cooked to order",
        price: 165.00,
        image: "https://via.placeholder.com/300x200?text=Filet+Mignon",
        stockQuantity: 18,
        thresholdLevel: 4,
        isAvailable: true,
        preparationTime: 24,
        isVegetarian: false,
        isSpicy: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Grilled Pork Chops",
        category: "mains",
        description: "Juicy pork chops with garlic mash",
        price: 98.00,
        image: "https://via.placeholder.com/300x200?text=Grilled+Pork+Chops",
        stockQuantity: 26,
        thresholdLevel: 5,
        isAvailable: true,
        preparationTime: 20,
        isVegetarian: false,
        isSpicy: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Roasted Chicken",
        category: "mains",
        description: "Herb roasted chicken with pan jus",
        price: 85.00,
        image: "https://via.placeholder.com/300x200?text=Roasted+Chicken",
        stockQuantity: 35,
        thresholdLevel: 6,
        isAvailable: true,
        preparationTime: 18,
        isVegetarian: false,
        isSpicy: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Grilled Salmon",
        category: "mains",
        description: "Atlantic salmon with lemon butter sauce and seasonal vegetables",
        price: 120.00,
        image: "https://via.placeholder.com/300x200?text=Grilled+Salmon",
    name: "Staff Member",
    email: "staff@dine-in.com",
    password: "$2a$10$D9Z.TP.B.4KM/0H6Hc1tKe7.Z5q5.q5q5q5q5q5q5q5q5q5q5q5q5q5", // password123
    role: "staff",
    phone: "+1 (555) 000-0002",
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date()
  }
]);
        name: "Fish and Chips",
db.menuitems.insertMany([
        description: "Crispy battered fish served with fries",
        price: 95.00,
        image: "https://via.placeholder.com/300x200?text=Fish+and+Chips",
        stockQuantity: 28,
        thresholdLevel: 5,
        isAvailable: true,
        preparationTime: 18,
        isVegetarian: false,
        isSpicy: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Shrimp Scampi",
        category: "mains",
        description: "Sauteed shrimp in garlic butter over linguine",
        price: 130.00,
        image: "https://via.placeholder.com/300x200?text=Shrimp+Scampi",
        stockQuantity: 22,
        thresholdLevel: 4,
        isAvailable: true,
        preparationTime: 16,
        isVegetarian: false,
        isSpicy: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Classic Cheeseburger",
        category: "mains",
        description: "Beef patty, cheddar, lettuce, and house sauce",
        price: 62.00,
        image: "https://via.placeholder.com/300x200?text=Classic+Cheeseburger",
        stockQuantity: 45,
        thresholdLevel: 8,
        isAvailable: true,
        preparationTime: 14,
        isVegetarian: false,
        isSpicy: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Club Sandwich",
        category: "mains",
        description: "Triple-layer sandwich with chicken, egg, and bacon",
        price: 58.00,
        image: "https://via.placeholder.com/300x200?text=Club+Sandwich",
        stockQuantity: 40,
        thresholdLevel: 8,
        isAvailable: true,
        preparationTime: 10,
        isVegetarian: false,
        isSpicy: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Chicken Panini",
        category: "mains",
        description: "Pressed panini with grilled chicken and cheese",
        price: 60.00,
        image: "https://via.placeholder.com/300x200?text=Chicken+Panini",
        stockQuantity: 35,
        thresholdLevel: 7,
        isAvailable: true,
        preparationTime: 11,
        isVegetarian: false,
        isSpicy: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Spaghetti Bolognese",
        category: "mains",
        description: "Classic spaghetti with rich beef bolognese",
        price: 72.00,
        image: "https://via.placeholder.com/300x200?text=Spaghetti+Bolognese",
        stockQuantity: 40,
        thresholdLevel: 7,
        isAvailable: true,
        preparationTime: 15,
        isVegetarian: false,
        isSpicy: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Lasagna",
        category: "mains",
        description: "Layered pasta bake with beef and cheese",
        price: 78.00,
        image: "https://via.placeholder.com/300x200?text=Lasagna",
        stockQuantity: 28,
        thresholdLevel: 5,
        isAvailable: true,
        preparationTime: 18,
        isVegetarian: false,
        isSpicy: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Pad Thai",
        category: "mains",
        description: "Stir-fried rice noodles with peanuts and tamarind",
        price: 80.00,
        image: "https://via.placeholder.com/300x200?text=Pad+Thai",
        stockQuantity: 32,
        thresholdLevel: 6,
        isAvailable: true,
        preparationTime: 14,
        isVegetarian: false,
        isSpicy: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Beef Ramen",
        category: "mains",
        description: "Rich ramen broth with noodles and beef slices",
        price: 76.00,
        image: "https://via.placeholder.com/300x200?text=Beef+Ramen",
        stockQuantity: 30,
        thresholdLevel: 6,
        isAvailable: true,
        preparationTime: 16,
        isVegetarian: false,
        isSpicy: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Macaroni and Cheese",
        category: "mains",
        description: "Creamy baked macaroni and three-cheese sauce",
        price: 55.00,
        image: "https://via.placeholder.com/300x200?text=Mac+and+Cheese",
        stockQuantity: 34,
        thresholdLevel: 6,
        isAvailable: true,
        preparationTime: 12,
        isVegetarian: true,
        isSpicy: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Pot Roast",
        category: "mains",
        description: "Slow-cooked beef pot roast with vegetables",
        price: 90.00,
        image: "https://via.placeholder.com/300x200?text=Pot+Roast",
        stockQuantity: 24,
        thresholdLevel: 4,
        isAvailable: true,
        preparationTime: 22,
        isVegetarian: false,
        isSpicy: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Meatloaf",
        category: "mains",
        description: "Traditional glazed meatloaf with gravy",
        price: 70.00,
        image: "https://via.placeholder.com/300x200?text=Meatloaf",
        stockQuantity: 25,
        thresholdLevel: 5,
        isAvailable: true,
        preparationTime: 15,
        isVegetarian: false,
        isSpicy: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Steamed Asparagus",
        category: "sides",
        description: "Lightly steamed asparagus with sea salt",
        price: 24.00,
        image: "https://via.placeholder.com/300x200?text=Steamed+Asparagus",
        stockQuantity: 30,
        thresholdLevel: 5,
        isAvailable: true,
        preparationTime: 6,
        isVegetarian: true,
        isSpicy: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Roasted Brussels Sprouts",
        category: "sides",
        description: "Caramelized Brussels sprouts with herbs",
        price: 26.00,
        image: "https://via.placeholder.com/300x200?text=Brussels+Sprouts",
        stockQuantity: 26,
        thresholdLevel: 5,
        isAvailable: true,
        preparationTime: 8,
        isVegetarian: true,
        isSpicy: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Sauteed Spinach",
        category: "sides",
        description: "Garlic sauteed spinach",
        price: 22.00,
        image: "https://via.placeholder.com/300x200?text=Sauteed+Spinach",
        stockQuantity: 28,
        thresholdLevel: 5,
        isAvailable: true,
        preparationTime: 6,
        isVegetarian: true,
        isSpicy: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Mashed Potatoes",
        category: "sides",
        description: "Creamy mashed potatoes",
        price: 20.00,
        image: "https://via.placeholder.com/300x200?text=Mashed+Potatoes",
        stockQuantity: 35,
        thresholdLevel: 6,
        isAvailable: true,
        preparationTime: 6,
        isVegetarian: true,
        isSpicy: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "French Fries",
        category: "sides",
        description: "Golden crispy fries",
        price: 18.00,
        image: "https://via.placeholder.com/300x200?text=French+Fries",
        stockQuantity: 50,
        thresholdLevel: 8,
        isAvailable: true,
        preparationTime: 6,
        isVegetarian: true,
        isSpicy: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Onion Rings",
        category: "sides",
        description: "Beer-battered onion rings",
        price: 19.00,
        image: "https://via.placeholder.com/300x200?text=Onion+Rings",
        stockQuantity: 35,
        thresholdLevel: 6,
        isAvailable: true,
        preparationTime: 7,
        isVegetarian: true,
        isSpicy: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Jollof Rice",
        category: "sides",
        description: "Ghana-style spiced tomato rice",
        price: 25.00,
        image: "https://via.placeholder.com/300x200?text=Jollof+Rice",
        stockQuantity: 45,
        thresholdLevel: 7,
        isAvailable: true,
        preparationTime: 10,
        isVegetarian: true,
        isSpicy: true,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Steamed Rice",
        category: "sides",
        description: "Fluffy steamed white rice",
        price: 16.00,
        image: "https://via.placeholder.com/300x200?text=Steamed+Rice",
        stockQuantity: 60,
        thresholdLevel: 10,
        isAvailable: true,
        preparationTime: 8,
        isVegetarian: true,
        isSpicy: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Garlic Bread",
        category: "sides",
        description: "Toasted garlic butter bread",
        price: 17.00,
        image: "https://via.placeholder.com/300x200?text=Garlic+Bread",
        stockQuantity: 40,
        thresholdLevel: 7,
        isAvailable: true,
        preparationTime: 5,
        isVegetarian: true,
        isSpicy: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Dinner Rolls",
        category: "sides",
        description: "Warm house-baked dinner rolls",
        price: 15.00,
        image: "https://via.placeholder.com/300x200?text=Dinner+Rolls",
        stockQuantity: 45,
        thresholdLevel: 8,
        isAvailable: true,
        preparationTime: 4,
        isVegetarian: true,
        isSpicy: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Artisanal Flatbread",
        category: "sides",
        description: "Wood-fired flatbread with olive oil",
        price: 21.00,
        image: "https://via.placeholder.com/300x200?text=Artisanal+Flatbread",
        stockQuantity: 30,
        thresholdLevel: 5,
        isAvailable: true,
        preparationTime: 8,
        isVegetarian: true,
        isSpicy: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Chocolate Cake",
        category: "desserts",
        description: "Rich chocolate cake with chocolate frosting",
        price: 28.00,
        image: "https://via.placeholder.com/300x200?text=Chocolate+Cake",
        stockQuantity: 25,
        thresholdLevel: 5,
        isAvailable: true,
        preparationTime: 2,
        isVegetarian: true,
        isSpicy: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Cheesecake",
        category: "desserts",
        description: "Baked cheesecake with berry compote",
        price: 30.00,
        image: "https://via.placeholder.com/300x200?text=Cheesecake",
        stockQuantity: 22,
        thresholdLevel: 4,
        isAvailable: true,
        preparationTime: 3,
        isVegetarian: true,
        isSpicy: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Fruit Tart",
        category: "desserts",
        description: "Seasonal fruit tart with custard",
        price: 27.00,
        image: "https://via.placeholder.com/300x200?text=Fruit+Tart",
        stockQuantity: 24,
        thresholdLevel: 4,
        isAvailable: true,
        preparationTime: 3,
        isVegetarian: true,
        isSpicy: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Assorted Pastries",
        category: "desserts",
        description: "Chef selection of daily pastries",
        price: 24.00,
        image: "https://via.placeholder.com/300x200?text=Pastries",
        stockQuantity: 28,
        thresholdLevel: 5,
        isAvailable: true,
        preparationTime: 2,
        isVegetarian: true,
        isSpicy: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Vanilla Ice Cream",
        category: "desserts",
        description: "Classic vanilla bean ice cream",
        price: 22.00,
        image: "https://via.placeholder.com/300x200?text=Vanilla+Ice+Cream",
        stockQuantity: 30,
        thresholdLevel: 5,
        isAvailable: true,
        preparationTime: 2,
        isVegetarian: true,
        isSpicy: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Chocolate Gelato",
        category: "desserts",
        description: "Dense Italian-style chocolate gelato",
        price: 24.00,
        image: "https://via.placeholder.com/300x200?text=Chocolate+Gelato",
        stockQuantity: 26,
        thresholdLevel: 5,
        isAvailable: true,
        preparationTime: 2,
        isVegetarian: true,
        isSpicy: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Mango Sorbet",
        category: "desserts",
        description: "Refreshing dairy-free mango sorbet",
        price: 23.00,
        image: "https://via.placeholder.com/300x200?text=Mango+Sorbet",
        stockQuantity: 25,
        thresholdLevel: 5,
        isAvailable: true,
        preparationTime: 2,
        isVegetarian: true,
        isSpicy: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Fudge Brownie",
        category: "desserts",
        description: "Warm chocolate brownie with fudge sauce",
        price: 26.00,
        image: "https://via.placeholder.com/300x200?text=Fudge+Brownie",
        stockQuantity: 28,
        thresholdLevel: 5,
        isAvailable: true,
        preparationTime: 3,
        isVegetarian: true,
        isSpicy: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Apple Pie",
        category: "desserts",
        description: "Classic apple pie with cinnamon",
        price: 27.00,
        image: "https://via.placeholder.com/300x200?text=Apple+Pie",
        stockQuantity: 22,
        thresholdLevel: 4,
        isAvailable: true,
        preparationTime: 3,
        isVegetarian: true,
        isSpicy: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Creme Brulee",
        category: "desserts",
        description: "Silky custard with caramelized sugar top",
        price: 32.00,
        image: "https://via.placeholder.com/300x200?text=Creme+Brulee",
        stockQuantity: 20,
        thresholdLevel: 4,
        isAvailable: true,
        preparationTime: 4,
        isVegetarian: true,
        isSpicy: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Iced Coffee",
        category: "beverages",
        description: "Cold brewed coffee with ice and milk",
        price: 18.00,
        image: "https://via.placeholder.com/300x200?text=Iced+Coffee",
        stockQuantity: 100,
        thresholdLevel: 10,
        isAvailable: true,
        preparationTime: 3,
        isVegetarian: true,
        isSpicy: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Passion Fruit Juice",
        category: "beverages",
        description: "Fresh passion fruit juice served chilled",
        price: 15.00,
        image: "https://via.placeholder.com/300x200?text=Passion+Fruit+Juice",
        stockQuantity: 80,
        thresholdLevel: 10,
        isAvailable: true,
        preparationTime: 3,
        isVegetarian: true,
        isSpicy: false,
        createdAt: new Date(),
        updatedAt: new Date()
      },
      {
        name: "Sobolo",
        category: "beverages",
        description: "Traditional hibiscus drink with ginger",
        price: 14.00,
        image: "https://via.placeholder.com/300x200?text=Sobolo",
    description: "Fresh romaine lettuce with Caesar dressing and croutons",
        thresholdLevel: 8,
    image: "https://via.placeholder.com/300x200?text=Caesar+Salad",
        preparationTime: 3,
        isVegetarian: true,
    isAvailable: true,
    preparationTime: 5,
    isVegetarian: true,
    isSpicy: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    name: "Chocolate Cake",
    category: "desserts",
    description: "Rich chocolate cake with chocolate frosting",
    price: 7.99,
    image: "https://via.placeholder.com/300x200?text=Chocolate+Cake",
    stockQuantity: 25,
    thresholdLevel: 5,
    isAvailable: true,
    preparationTime: 2,
    isVegetarian: true,
    isSpicy: false,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    name: "Iced Coffee",
    category: "beverages",
    description: "Cold brewed coffee with ice and milk",
    price: 4.99,
    image: "https://via.placeholder.com/300x200?text=Iced+Coffee",
    stockQuantity: 100,
    thresholdLevel: 10,
    isAvailable: true,
    preparationTime: 3,
    isVegetarian: true,
    isSpicy: false,
    createdAt: new Date(),
    updatedAt: new Date()
  }
]);

db.tables.insertMany([
  {
    tableNumber: 1,
    capacity: 2,
    status: "available",
    location: "main",
    currentOrder: null,
    currentReservation: null,
    notes: "Window seat",
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    tableNumber: 2,
    capacity: 4,
    status: "available",
    location: "main",
    currentOrder: null,
    currentReservation: null,
    notes: "",
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    tableNumber: 3,
    capacity: 6,
    status: "available",
    location: "main",
    currentOrder: null,
    currentReservation: null,
    notes: "Good for groups",
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    tableNumber: 4,
    capacity: 2,
    status: "available",
    location: "patio",
    currentOrder: null,
    currentReservation: null,
    notes: "Outdoor seating",
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    tableNumber: 5,
    capacity: 8,
    status: "available",
    location: "private",
    currentOrder: null,
    currentReservation: null,
    notes: "Private dining room",
    isActive: true,
    createdAt: new Date(),
    updatedAt: new Date()
  }
]);

print("Seed data inserted successfully!");
